### ISSUE TITLE
Scripting for "Delta Shift"

### ISSUE THREAD

**Issue by CrazyVulcan** [KFNEXUS/KFNEXUS.github.io#13]
We need some Java Scripting for ID: "delta_shift_cairo" to make it so it can be equipped without taking up a slot. I suggest that it be made to just duplicate whatever slot it is placed in. Example if I put Delta Shift in a Tech slot another Tech slot is created for the ship it is placed on.

**Comment by jsterner73** [comment]
Fixed with commit [581c27dbc80a2ba18cd79bd410375db6e808dce2](https://github.com/KFNEXUS/KFNEXUS.github.io/commit/581c27dbc80a2ba18cd79bd410375db6e808dce2)
