### ISSUE TITLE
Scripting for "Fleet Commander" resource needed.

### ISSUE THREAD

**Issue by CrazyVulcan** [KFNEXUS/KFNEXUS.github.io#17]
Now THIS is going to be a pain to get working right. Here is the card text.

"One ship in your fleet may have a 2nd Captain assigned to it. That ship may use both of its Captain's Abilities as normal throughout the game. The overall Captain Skill Number of the ship is equal to the highest Captain Skill of its Two Captains plus 1. In addition, the ship to which the 2nd Captain is assigned gains +1 to either its Shield or Hull value (max 6 Hull). This decision must be made at the start of the game during the Gather Forces step and cannot be changed for the remainder of the game."

My thinking would be to be when you select this resource a new slot in every ship you have that can fit a captain. I also dont think we need necessarily add the +1 shield or Hull to show on the card but the choice may be neat. Also it should no be too hard to have the CS go up by +1 to the highest of the two captains like it does with admirals.

**Comment by pantner** [comment]
Perhaps have 2 slots appear for every ship, one that gives you a +1 to Hull, the other to shields.

You'd also need to add the resource cost to that ship, so maybe add a 5 SP penalty to that second captain and make the resource SP cost '0' (with a note saying that it will add 5 SP to the ship that you add the second captain to?)

**Comment by tsuyoshikentsu** [comment]
Actually, I think the best workaround would be to do what's currently done with the Fleet Captain resource--slot the resource itself into the Resource slot for 0 points, which creates a "Fleet Captain" slot on all ships. Then have there be another, separate card that only goes in Fleet Captain slots that grants +1 hull/+1 shield/+1 CS (to all captains on the ship, if nothing else works) and adds a captain slot.

**Comment by CrazyVulcan** [comment]
tsuyoshikentsu, I was thinking along the same lines as you. Just have a
card that adds +1 Shield, and one that adds +1 Hull. But adding the
captains is where I seem to have the issue. I would like it to act like the
admiral where every ship has a second captain slot till one is filled. But
I lack the needed skills to do so.

Creating a new class in the json is easy. It is just adding that 2nd
captain in the cardrules.js I can not get to work.

**Comment by CrazyVulcan** [comment]
I need a workaround to get the cost 5sp to the ship the 2nd captain attaches to but you can now use Fleet Commander.
