### ISSUE TITLE
A help request for GIT

### ISSUE THREAD

**Issue by CrazyVulcan** [KFNEXUS/KFNEXUS.github.io#20]
So I have been working on some javascript changes, mostly for teaching myself through trial and error but I have noticed that something weird is happing when pushing the changes to the live build. And I have had a lot of issues, mostly from what I believed was my own lack of experience. But the other day when I updated the data.json. I had to make a correction and when I did the GIT said that it was synced. But my changes were not showing up on my browser. Sometimes it worked after a few seconds or minutes. Sometimes I noticed that changes would take hours to take effect. 

This is why you see me posting change after change on the ledger. I generally strive for getting it right the first time but sometimes I notice changes that need to be made. And then feel frustrated as they seem to not work, So I look and try again

I found a workaround to this issue last night and it works every time. But it involved clearing my history and cookies to "flush" out the old build that was saved in my chrome cache. Does anyone know any suggestions? As I typically don't like going trough my annoyance from Chrome.

-Christopher

**Comment by jsterner73** [comment]
I have this sometimes as well.

You can check the changes locally as well - there's a trick with the Chrome browser to accept local files:

"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --allow-file-access-from-files

Try this, so you can see your changes before you push it to GitHub.

Hope this helps

Joerg

**Comment by CrazyVulcan** [comment]
Thanks Joerg, I seem to have solved the issue. Now if only the Javascript would be as cooperative. But now I can sleep comfortably knowing that this works. Sometimes I think I had the answer but because I could not see the most up to date live version there are probably a number of things I need to retry to be sure.

Speaking of js could anyone reason why this is not working. It is for the Duras sisters. If one is the captain then you can fill a crew slot with the other and gain +4 Captain Skill. And they are exclusive so you can't equip one if the other is not.

`		"crew:lursa_crew_72282p": {		
			intercept:{
			self:{
				canEquip: function(upgrade,ship,fleet){
					if (ship.captain && ( ship.captain.name == "B'Etor") )
						return true;
					return false;
				},
				skill: function(upgrade,fleet,skill){
					return resolve(upgrade,ship,fleet,skill) + 4;
				return skill;
				}
			}
			}
		},

Night everyone`

**Comment by CrazyVulcan** [comment]
Hey all, just an update I just learned yesterday why Utopia was not loading my changes despite doing everything I thought of from clearing my history and cookies to running my own apache server. When using Chrome it will not reset the files even if you use Ctrl+F5 and or set network to disable caching. First, enter the inspector, RMB>Inspect. Second Right Click on the refresh button on your URL. Select "Empty Cache and Hard Reload"

NOTE that this only can be done when the page inspector is open! Google change this about 6 months back and have not been very good about communicating it with their developer users.
