### ISSUE TITLE
Hatchery not adding slots

### ISSUE THREAD

**Issue by tsuyoshikentsu** [KFNEXUS/KFNEXUS.github.io#21]
Hey all--Tucker from SotF and BS here. :-) Hatchery isn't adding either its normal Crew slot or its facedown Quark slot. I'd help if I could, but I don't know JS. :-(

**Comment by jsterner73** [comment]
Fixed with commit [0ee2b450571ff92dc9d523da2dd91329acfb904a](https://github.com/KFNEXUS/KFNEXUS.github.io/commit/0ee2b450571ff92dc9d523da2dd91329acfb904a)
