### ISSUE TITLE
Picard (8) from Yesterday's Enterprise Not discounting

### ISSUE THREAD

**Issue by pantner** [KFNEXUS/KFNEXUS.github.io#23]
I've noticed that the new Picard from the Yesterday's Enterprise prize does not discount any upgrades and the "-2 for the ship" actually comes off his own cost.

**Comment by SpinStabilized** [comment]
I've fixed this issue and it can be closed.

**Comment by CrazyVulcan** [comment]
Thank you again SpinStabilized, you're amazing.
