### ISSUE TITLE
Battlestation icons showing as Borg Slot icon

### ISSUE THREAD

**Issue by pantner** [KFNEXUS/KFNEXUS.github.io#24]
For as long as I have been using Utopia, card text that has a battlestation icon in it actually shows a borg slot icon.

As an example, The Federation ET: Disobey Orders

**Comment by jsterner73** [comment]
For me it looks like this in Google Chrome (version 57.0.2987.133):

![image](https://cloud.githubusercontent.com/assets/13046935/24826246/9e20303a-1c31-11e7-8057-0ac76573a371.png)

And this is the same card in Microsoft Edge/IE (version 38.14393.0.0):

![image](https://cloud.githubusercontent.com/assets/13046935/24826268/ea5065ec-1c31-11e7-8613-906bc49d0793.png)

So there's a problem with Edge/IE showing the wrong icon.

**Comment by pantner** [comment]
I think I know what it is.

Both the Borg and Battlestations CSS use a "b" to identify the content. BS is a capital, borg is a lowercase b.
ie
fs-borg:before{content:"b"}
fs-battlestations:before{content:"B"}

All Microsoft products treat upper and lower case letters/words as the same letter/word.

On a Linux/Mac you can have a folder called 'TEST' and a folder called 'test' and they separate.
On a Windows computer you can't do that.

Hope that makes sense.
To fix it you will need to change one of them to a different letter. (not sure if you can use BS for battlestation? is there a proper reason it is only one letter?)

**Comment by jsterner73** [comment]
Thanks for the hint with the CSS assignment.

I'm looking into how to edit a TTF file, do you have a recommendation?

As for the 'why', I'm not the original deisgner/coder of this program I merely fix and stuff to my best knowledge. I've come across many things I still do not understand in the code, so I sometime just do trial-and-error locally until they work as I want them to.

**Comment by pantner** [comment]
Well, that's just a guess but it seems to be right.

I've never done it before, I didn't realise that it used a font to show the symbols.

A quick google shows a few free programs, not sure if any of them are any good?

As a test, maybe change Disobey orders to show a different symbol that it normally wouldn't (regenerate?) and make sure that changing it works (ie, there could be something else in the CSS that does it, but it does make sense to me that it is the lowercase/uppercase that is causing the issue.According to IE/Edge that "b" reference is in there twice, it just happens that the Borg entry is after the battlestation entry. You could also swap them around in the CSS, see what happens if you put the BS entry after the Borg entry. All the Borg stuff should show as BS icons in IE/Edge)

**Comment by jsterner73** [comment]
Should be resolved now (with commit [1ae8ac8f6f0c1ffc721eb6dc9b2ed3646677c82e](https://github.com/KFNEXUS/KFNEXUS.github.io/commit/1ae8ac8f6f0c1ffc721eb6dc9b2ed3646677c82e).

@pantner can you please check if it's working for you as well? if it is, please close the issue

btw: the tool I finally used to change the TTF file was [Type light](http://www.cr8software.net/typelight.html) (for future reference)

**Comment by pantner** [comment]
Awesome, all looks good to me :)
Thanks!
