### ISSUE TITLE
News from Origins !!!! Lots of Errata and new card formats!

### ISSUE THREAD

**Issue by CrazyVulcan** [KFNEXUS/KFNEXUS.github.io#27]
https://www.facebook.com/stateofthefederation/photos/a.994221787277822.1073741829.798688490164487/1601225193244142/?type=3&theater

Origins and its Wizkids fan apreashion conference have finished and now we are looking over the news. Among many of the new things, they have planned. We have a fair amount of work ahead of us to undertake to start in about mid-August. One with the new rulebook are a lot of text and number changes planned for many if not all the cards currently in the game. This will mean a good deal of editing the data.json to reflect the changes that may be released gradually or I expect to be all at once. 

I, however, am a really an insomniac who will likely not be able to focus elsewhere in my life with this to undertake. Anyone who want to volunteer to divide and conquer I am happy for it and most importantly I am not to good at transcribing large amounts of text. With to speak honestly I guess to be an 80% reliability per card. So having someone go over and proofread and check will be important. 

And with the new cards comes a new updated style that I will like to emulate as closely as possible. To make things more clear they are replacing a lot of the worded text which is often inconsistent in its writing. The are now going to be using icons to replace common words. The few I am able to confirm with the released work in progress art are the following

"Auxiliary Power Tokens" will be replaced with a colored symbol much like [evade] [target-lock] etc. I want to add this new image into the existing library and call it with [aux]. Which I am happy as it was very tedious to write it out without a typo like a misspelling Auxiliary or my common TOkens one

"Time Tokens" now will be just like Aux Tokens. I would like to use [time] for them.

"Weapon firing arcs description text is now going to have on the right-hand side a red triangle denoting forward or aft based on its direction. These are easy enough to add to the json I just need to add the lines "forward arc" : true, "rear arc" : true,

Tech, Crew, and Captains will need to have the "range" : "1-2", added where needed

There is now a special type of "unique" that will now include "one per ship" along with unique and mirror unique. 

This will be a challenge as now instead of saying a card can only go one one class of ship there will be a picture of the silhouette that is on the ship card but not Utopia. My alternative is to simply write the class name on the bottom of the card like it is now only just using keywords for clarity. 

That should cover all the CSS changes that we will need to make. I can easily whip up small pixel images to take the place of the new art but of course, I am unfamiliar with creating a new class and getting it to work with the program. I feel they will need to be added in the angel.js or the other one in order for it to work. 

There is a lot of work the is ahead and Jjsterner73 ? Kfnexus? are you still with me one this project? It seems like a mountain to climb be it will be done.

**Comment by jsterner73** [comment]
Hi, thanks for the update.

As for the cards changes, I can do those if you are not feeling confident. It may take some time, but I guess we'll be getting there.

As for the new icons - do you have a programm to edit those? I remember search last time I changed something in there and it was quite hard to find one that was compatible to the version that was used already. You might want to check on the resolved issues, I think I mentioned there which programm it was.

Do you have visual examples of the things you described in your post? Is there a link to those I can look at?

Otherwise, thanks for bringing this up and I think we will be good and implement those changes in Utopia.

**Comment by jsterner73** [comment]
I think I found one of those pictures: [example card](https://scontent-vie1-1.xx.fbcdn.net/v/t31.0-8/r270/19221674_1601225389910789_2117891466262351734_o.jpg?oh=e251b136fc635c2cf0d40c58527e0f00&oe=59DD2642)

**Comment by KFNEXUS** [comment]
Hi, thanks for the news! i does not have a lot of time now. But i try to find a moment to do something.

**Comment by JamesBess** [comment]
Wouldn't firing arcs need 4 icons?
forward 90
rear 90
360
forward 180  (no rear 180 is there?)

**Comment by JamesBess** [comment]
I looked at the .json and here are my suggestions for modification

**shipClasses**:
--add pointer to "classIcon" image
--remove "frontarc" and "reararc" 
--add array for "arcs" values to be [front90, front180, 360, rear90] (is there a rear 180 ship??)

**upgrades:**
--add string for "range"
--add array for "arcs" values to be [front90, front180, 360, rear90] (is there a rear 180 ship??)
--will need boolean for "one per ship"
--add "classlimited" that can be set to "id" in "shipClasses"

**captains**:
--add "classlimited" that can be set to "id" in "shipClasses" (not sure if this will be required yet, have not seen any captain cards yet"
--add string for "range"

**admirals**:
--add "classlimited" that can be set to "id" in "shipClasses" (not sure if this will be required yet, have not seen any admiral cards yet"
--add string for "range"

I am not sure how much the arc change will effect the rest of your code, but I think that changing to array will prevent you from any major changes down the road. Whichever way you decide to go, i will be happy to do the data input and/or checking.

**Comment by CrazyVulcan** [comment]
JamesBess, yes an array will be better for handling arc. They are already present in ship classes as the work into the graphic above the movement card. The new ones are upgrades and simply replace where the text used to say "This weapon may be fired from your forward or rear firing arc." or "This weapon may be fired in any direction" Thinking but we might need to add one for "not in your forward arc" but I will need to see one example of how they represent that. They are looking as though they are placing these alongside the left hand side of the cards. 

Adding a "classlimited" line should be simple enough but doing so will mean adding all the infographics for each class. 

jsterner, I got the graphics covered they need to be low resolution for load time but I can get them uploaded in a day or two. When I find an hour or so to do them. I am just unsure how making the pointers for them work but I am excited to learn.

**Comment by JamesBess** [comment]
Chris they have a picture of one of the upgrade cards with the graphis arc on the card, that is why i was thinking "arcs" would need to be in the upgrades also.  here is a link to the upgrade card in question.
https://scontent-atl3-1.xx.fbcdn.net/v/t31.0-8/19144060_1601225193244142_7950052210061841089_o.jpg?oh=17ce0df131d33eedb74aad55f1f69ea0&oe=59DE3AD9

**Comment by CrazyVulcan** [comment]
James the arcs for ship class has nothing to do with the firing arc graphics. You do not want to remove them from ship classes because then it will break the graphic that appears over that ships movement card. This red triangle will only appear on Upgrade cards where it needs to specify where a ship can fire it from. And so they need to be their own thing.

**Comment by JamesBess** [comment]
I thought that they were putting the arc on the new ship cards, but after going back and looking at the new ship cards released they do not.  So as you say, shipClasses would not need to be modified.  Now realizing this, I would hazard a guess that upgrade cards will have only 3 choice for arc: "forward", "rear", and "360".  I am guessing that the icon will look like a 90deg cone up, 90deg cone down, and a full circle (like on the plasma pulse card shown)  but will equate to whatever the ship has for forward/rear arc.

**Comment by CrazyVulcan** [comment]
I have added the new symbols for the text update. There is now an Aux symbol in place of character '2' and one for time in place of '3'. The branch still needs to be merged and Grunted as I have never edited the .tts file type and don't want to break it accidentally.

**Comment by CrazyVulcan** [comment]
Added the new art in the src folder for forward and rear arcs to be used with upgrades where that is specified. All that should need to do is put them on top of the stack in CSS when they are called in the data.json. They have a gray border and black background that should blend in nicely and not look out of place. More will be coming for 'One per Ship' and '360 Arc'. As well as any new ones we learn about

**Comment by CrazyVulcan** [comment]
GUYS LOOK I DID A THING!!! And I figured it out all by myself. There are now symbols in the font for [aux] and [time] tokens

**Comment by KFNEXUS** [comment]
Cool!

**Comment by CrazyVulcan** [comment]
Also looking at the new cards we need to include a graphic with hull
restrictions.

**Comment by JamesBess** [comment]
Can you check formatting on time token icon and aux token icon.   I shows on my screen partial overlapping the text leading and following.  Rest of the icons appear to be fine, just those two.

**Comment by CrazyVulcan** [comment]
The formatting has been fixed.

**Comment by CrazyVulcan** [comment]
Holy SHIT guys look I did another thing! Now the CSS for the One Per Ship is working. You know it's almost like I have learned something. http://kfnexus.github.io/staw-utopia/set-viewer.html#72014wp

**Comment by CrazyVulcan** [comment]
Hey just got back from my trip. The new rules dropped today and I will be needing help getting the changes to faction penalty into the utopia.min.js file. Not sure where to even begin.

**Comment by KFNEXUS** [comment]
> utopia.min.js
May be just add dual faction to all upgrades that need no faction penalty. For example Bajor  give a Bajor/ fed dual fection etc.

Not only faction penalty, but +3 and -3 rule need to be inplemented too.

**Comment by CrazyVulcan** [comment]
Damn it.... I did not even think of Rule of 3. That would be an ideal to have but not a priority. Just have to trust players keep the new rule in mind. Also, I CAN add the faction penality excluder to the upgrades. BUT I would have to add it to every card and that will double the size of the file. I would like to try to add just one block of code that does all of the work. JamesBess Any idea of how to do that? 

There has to be a way to say when applying the faction penality exclude it for X and Y faction.

**Comment by CrazyVulcan** [comment]
After pondering on it. Yes, we will have to add exceptions for each card on a case by case basis. For cards that add a penalty for not being equipped on a certain races ship means we cant have a blanket code that works universally. 

I can do this, it will just take time. Give me until the 23rd and I think I can get it all updated.

**Comment by CrazyVulcan** [comment]
I have a good idea how to go about this. I will just remove the faction penilty for the other factions on each card. The issue I am running into though is that I cant get Picard 9 to be placed in a Vulcan AND a Bajoran ship. Here are a few things I have tried below
"captain:2001":{
			factionPenalty: function (a, c, d) {
				return c && b.hasFaction(c, "vulcan", c, d) ? 0 : 1
			},
                        factionPenalty: function (a, c, d) {
				return c && b.hasFaction(c, "vulcan", c, d) ? 0 : 1
			}
		},

"captain:2001":{
			factionPenalty: function (a, c, d) {
				return c && b.hasFaction(c, ["vulcan","bajoran"], c, d) ? 0 : 1
			}
		},

"captain:2001":{
			factionPenalty: function (a, c, d) {
				return c && b.hasFaction(c, ("vulcan","bajoran"), c, d) ? 0 : 1
			}
		},

**Comment by CrazyVulcan** [comment]
I have the sub-factions working its just going to take some time to get all
the cards updated. Unless you have a faster way. I am pretty much adding
this line to each upgrade

"captain:maxwell_forrest_cap_71526":{
factionPenalty: function (a, c, d) {
return c && b.hasFaction(c, "vulcan", c, d) ? 0 : 1 && b.hasFaction(c,
"bajoran", c, d) ? 0 : 1
}
},

With this I can put him on any Vulcan or Bajoran ship without the penalty.
I am just doing this for each Federation, Bajoren, Vulcan, Indipendent,
Kazon, Xindi, and Ferengi. Upgrades. But maybe there is a faster way with
less code?

As far as the Icons I have been experimenting with CSS and text but I also
think it would be easier to just put an image in the needed spot. I
currently have two images called; upgrade-forward-arc.png,
upgrade-rear-arc.png, and upgrade-hull-limit.png

**Comment by CrazyVulcan** [comment]
@jsterner73 
I have the sub-factions working its just going to take some time to get all the cards updated. Unless you have a faster way. I am pretty much adding this line to each upgrade

"captain:maxwell_forrest_cap_71526":{
			factionPenalty: function (a, c, d) {
				return c && b.hasFaction(c, "vulcan", c, d) ? 0 : 1 && b.hasFaction(c, "bajoran", c, d) ? 0 : 1
			}
		},

With this I can put him on any Vulcan or Bajoran ship without the penalty. I am just doing this for each Federation, Bajoren, Vulcan, Indipendent, Kazon, Xindi, and Ferengi. Upgrades. But maybe there is a faster way with less code?

As far as the Icons I have been experimenting with CSS and text but I also think it would be easier to just put an image in the needed spot. I currently have two images called; upgrade-forward-arc.png, upgrade-rear-arc.png, and upgrade-hull-limit.png

**Comment by jsterner73** [comment]
@CrazyVulcan I havent't been around the last few days, so I'm not up-to-date what the new rules / rule changes are - is there a summary of how the new faction penalties are calculated?

**Comment by wiegeabo** [comment]
The big change being worked on is the new sub factions.

All Bajoran and Vulcan cards are now essentially dual faction with
Federation.

All Kazon, Ferengi, and Xindi are effectively dual faction with Independent.

**Comment by jsterner73** [comment]
In the file _utopia-card-loader.js_ there's code for calculating the faction penalty

```
ship.intercept.ship.cost.push( {
	source: "Faction Penalty",
	priority: 1,
	fn: function(upgrade, ship, fleet, cost) {
		if( !$factions.match( upgrade, ship, ship, fleet ) ) {
			var penalty = valueOf(upgrade,"factionPenalty",ship,fleet);
			return (cost instanceof Function ? cost(upgrade, ship, fleet, 0) : cost ) + penalty;
		}
		return cost;
	}
});
```
Perhaps it's best to try and tweak that one instead of added code to every single effected card.

**Comment by CrazyVulcan** [comment]
Don't worry about it I am about 1/2 way through all the cards, just give me a few days to finish. Quick question. I know Vulcan and Bajoran cards can go on a fed ship and visa versa but can Vulcan cards go on a Bajoran ship without a faction penalty?

**Comment by JamesBess** [comment]
The general consensus is that in essence vulcan cards are now vulcan/federation and bajoran is bajoran/federation and since they are part federation then yes they can go on each other with no penalty.  The argument has been if a card that is sub-faction specific can be placed on another sub-faction ship I.E. can [Bajoran Militia] be placed on a vulcan ship.  The answer to this I am not sure.

**Comment by CrazyVulcan** [comment]
@JamesBess Ok, but for the time being, I am going to go with yes they can. As it is just as easy to delete the excess code from the Bajoran and Vulcan upgrades then it is to add them.

**Comment by wiegeabo** [comment]
Bajoran Militia can't go on a Vulcan or Fed ship.

That's been the consensus. While the new sub faction gets around faction
penalty, it doesn't get around faction specific text.

So, similarly, Vulcan High Command can't go on a Bajoran or Fed ship.

**Comment by JamesBess** [comment]
It is certain that sub-faction specific cards cannot go on prime faction ships.

It has been mostly agreed that Prime faction specific cards can go on sub-faction ships (i.e. Systems Upgrade can be used on bajoran/vulcan ships). 

What is being argued is whether or not sub-faction specific cards can go on another sub-faction.  The rulebook states 

> Game elements belonging to a sub-Faction also count as their
prime Faction for the purposes of all rules. However, prime
Faction ships do not count as their sub-Factions unless otherwise
stated.
> 

This seems to say that basically ALL bajoran cards are now dual faction marked Bajoran/federation and all Vulcan cards are dual faction Vulcan/Federation.  But Federation are still just federation.  Therefore Bajoran ships should not be able to use Vulcan High Command.  Only issue is that some are reading the part of rulebook that only mentions the "prime faction ships" part and think that sub-factions should be able to do it.  Personally I feel that sub-faction specific cards CANNOT go on a different sub-faction ship, but that is only my opinion.

**Comment by CrazyVulcan** [comment]
So if I put Kira Neris on a Galaxy class, I would not pay a faction penalty. But putting Picard on a Bajoran Interceptor I would have to pay a faction penalty? Forget aside things that say it can only go on a sub-faction, that is clear that they can not go on the main ship. But why can Federation upgrades not go on a Bajoran or Vulcan ship and have to pay a penalty?

I am not thinking about specific cards I mainly want to know if I put a Vulcan captain, without any kind of restrictions. Can I then put him on a Bajoran ship without paying a faction penelity?

**Comment by wiegeabo** [comment]
Faction penalties are no longer a thing between a faction and it's sub
factions.

Essentially, every card in the Fed sub faction has a Fed symbol on it now,
and is dual faction. The symbols on Fed cards themselves are unchanged.

So, a Vulcan card can go on a Fed or Baj ship with no penalty. A Baj card
can go on a Vulcan or Fed ship without penalty. Fed cards can go on Baj and
Vul without penalty.


The trick is ship specific cards. Vulcan High Command says it can only be
assigned to a Vulcan captain on a Vulcan ship. So it cannot be placed on
Baj or Fed ships, even though they share faction. And even if they were
assigned a Vulcan captain. Just like how Phaser Strike can only be placed
on a Bajoran Interceptor ship, even though it's a Bajoran card. Because it
doesn't just say Bajoran ship, but specifies Interceptor, it's confined to
that class.

So Bajoran Militia can't be placed on Vulcan or Fed ships.

**Comment by JamesBess** [comment]
in answer to your question Vulcan, yes you can put a no restriction vulcan captain on a bajoran ship and you do NOT pay faction for it.

And I agree 100% with what Wiegaebo says on faction specific cards

**Comment by CrazyVulcan** [comment]
Ok then at least we 3 are in agreement, and like I said we can always go back and correct. I started with the core set and I just finished wave 21. This has also allowed me to better organize and comment the min.js file. Comatose did a great job when he set this up but his documentation and his organization left some to be desired.

**Comment by CrazyVulcan** [comment]
Well, it took me about 10 hours and I know I said I gave myself to the end of the week but.... I have compulsion issues and could not relax with this to do. I also took the time to organize the utopia.min.js file so all the ships that have rules attached to them appear in order of release and are grouped by expansion. Need to find something just search the file for the ship you are looking for. No more having to look at the data.json file for the ID then searching the min.js file for the string you just looked up. There are other upgrades that are floating free still but I have put in enough work for tonight and need to sleep. 

Please note I did a lot of changing and there might be bugs still that I have yet to notice. I tried checking everything as I went along but I know I missed something.

**Comment by CrazyVulcan** [comment]
@jsterner73 @KFNEXUS 
Hey, I was wondering if I can get some help getting Calvin Hudson working again. I lost the original file I was editing that had the working code. And I am having issues with recreating what I previously had done. He will discount any Ferengi, Kazon, Xindi and Indy cards equipped to his ship but I am having an issue with him only being able to do it on one of those factions ships. If you put him on a fed ship he takes a penalty but putting say Xindi Torpedoes on that ship he will subtract 1sp. 

`// Calvin Hudson
		"captain:calvin_hudson_71528": {
			factionPenalty: function(upgrade, ship, fleet) {
				return ship && $factions.hasFaction( ship, "ferengi", ship, fleet ) ? 0 : 1 && $factions.hasFaction( ship, "kazon", ship, fleet ) ? 0 : 1 && $factions.hasFaction( ship, "xindi", ship, fleet ) ? 0 : 1;
			},
			upgradeSlots: [ 
				{ 
					type: ["tech","weapon","crew"]
				}
			],
			// Reduce cost of all Upgrades by 1 SP if on Independent ship
			intercept: {
				ship: {
					// Reduce cost of all Upgrades by 1 SP if on Independent ship
					cost: function(upgrade, ship, fleet, cost) {
						if( isUpgrade(upgrade) && ( ship && $factions.hasFaction(upgrade,"independent", ship, fleet) || $factions.hasFaction(upgrade,"ferengi", ship, fleet) || $factions.hasFaction(upgrade,"kazon", ship, fleet) || $factions.hasFaction(upgrade,"xindi", ship, fleet) ) )
							return resolve(upgrade, ship, fleet, cost) - 1;
						return cost;
					},
				}
			}
		},`

**Comment by jsterner73** [comment]
Sorry for the late answer, but have you checked in your changes before? If so, you can look through the git commits until you find your changes.

As for the question itself, doesn't he reduce all upgrade if he's on an independent ship? Not only independant upgrades?

**Comment by wiegeabo** [comment]
Yes. As long as as it’s Indy.  This includes talents and question mark
upgrades. And even those that don’t take a slot, like Delta Shift and
Maintenance Crew.

**Comment by CrazyVulcan** [comment]
Ok I got him working with indy ships, but I still am stumped with getting him to work on Ferengi, Kazon, or Xindi ships.

**Comment by wiegeabo** [comment]
What do you mean. His ability, or his ability when paired with Captured?

**Comment by CrazyVulcan** [comment]
@wiegeabo He is working on indy ships, but since sub-faction ships count as their main faction his effect should also work on the other 3 factions.

**Comment by CrazyVulcan** [comment]
My goal this week is getting the CSS for the forward and rear firing arc restriction working. I have the new symbols in the font and I could do as I have but I really want to see if I can get the pictures working and in the right places.  

Also speaking of CSS any idea what I need to do to get the OnePerShip limit symbol working right? The name text should be shifted to the right by about 0.1em and there should be a black rectangle that trims the inner corner on the card.

**Comment by CrazyVulcan** [comment]
OK I am stumped on what it is wanting me to do to get the Forward and Rear Arcs working correctly. I posted what I have done so far but if someone gets some free time could you look over and see what I am missing?

@KFNEXUS @jsterner73 @JamesBess

**Comment by CrazyVulcan** [comment]
I doubt it is the most sophisticated way of solving the formatting issues but I feel this will do. At least they look correct and I may end up deleting the font elements that are no longer needed.
