### ISSUE TITLE
Typos and formatting fixes for card pack

### ISSUE THREAD

**Issue by wiegeabo** [KFNEXUS/KFNEXUS.github.io#34]
I've created a pull request for a number of fixes to card pack text.

**Comment by wiegeabo** [comment]
#32

**Comment by CrazyVulcan** [comment]
@wiegeabo I have edited in your changes into Utopia. Please remember to only edit the files in the src folder as anything in the staw-utopia folder will get written over every time one goes to make an update. I myself only recently learned to do it in the correct way.
