### ISSUE TITLE
Ship Specific Resources

### ISSUE THREAD

**Issue by CrazyVulcan** [KFNEXUS/KFNEXUS.github.io#43]
It seems almost every new resource these days is only equipable to one ship in your fleet. Fleet Commander, Captains Chair, Front Line Retrofit. I want the ability to equip these resources directly to a ship. I have been working on it for most of the last two days and had no progress. I can add an extra free Upgrade slot to any ship but this is not working with ships as then all cost come back with a NaN (not a number) error. Any ideas on how to get this to work?

I am currently trying to duplicate the Admiral slot and rewrite it to be a Resource slot. But I need to walk away from it for a bit and get some fresh air.

@KFNEXUS @jsterner73 @FND

**Comment by FND** [comment]
Could you push your work-in-progress changes to a temporary Git branch so I can have a look? I'm not very familiar with the Angular application (having mostly worked on the data side of things so far), so that diff _might_ help me get my bearings, figuring out what's where etc. (no promises though).

**Comment by CrazyVulcan** [comment]
@FND Sorry, I pushed the last update before reading this, I will hold off on more until at least Monday. I will be honest that Angular.js page is a complete mystery to how it works.

**Comment by FND** [comment]
That's quite alright; thanks to [the diff](https://github.com/KFNEXUS/KFNEXUS.github.io/compare/678f7ad1ddbd526a3039af726b9fa552d8b7eacb...master), I now understand that `src/js/common/utopia-card-rules.js` contains special rules determining cards' suitability, cost etc. - however, that seems like a small part of the puzzle, so I'll keep monitoring changes to perhaps learn more about the inner workings of Utopia.

**Comment by CrazyVulcan** [comment]
Ive tried adding a Resource slot to the starter Enterprise D But any resource added there would result in the NaN error I mentioned earlier. 

There is a way I know it can work but is a bit labor intensive. Merge Fleet Captain, Flagship, Officer ect and add a proxy to say Fleet Commander to that list. That or add a new category that is just for the ship resources and add a slot for them to each ship. 

There are ways but adding the ability to add a resource to a ship is likely the least work. My only concern that is because it is not included in the Upgrades list it will not function as it should.

**Comment by CrazyVulcan** [comment]
I got it working by creating a new section of cards called "ship-resource" and made the new resources cost 0sp and spawn a slot for their corresponding cards. Let me know what you think.
