### ISSUE TITLE
Captain's Chair with Captain Skill less than 5

### ISSUE THREAD

**Issue by Cerender** [KFNEXUS/KFNEXUS.github.io#47]
Captain's Chair ship resource can be added to a ship with any level Captain Skill.

This resource is restricted to Ships with Captain Skill 5+

![screen shot 2018-06-13 at 3 37 40 pm](https://user-images.githubusercontent.com/7477346/41375169-39b2c4dc-6f23-11e8-93ca-25c51a95ae4f.png)
![screen shot 2018-06-13 at 4 01 39 pm](https://user-images.githubusercontent.com/7477346/41375170-39c2dffc-6f23-11e8-92eb-858d719fe4bf.png)

**Comment by CrazyVulcan** [comment]
FIxed with comment 8caf27a
