### ISSUE TITLE
IKS AMAR set view shows 2 "Photon Torpedoes" cards

### ISSUE THREAD

**Issue by Cerender** [KFNEXUS/KFNEXUS.github.io#49]
http://kfnexus.github.io/staw-utopia/set-viewer.html#72232

There should only show one Photon Torpedoes card. 
https://wizkids.com/attackwing/wp-content/uploads/sites/4/2016/02/72327_IKS_Amar.jpg
https://www.boardgamegeek.com/image/2936797/star-trek-attack-wing-iks-amar-expansion-pack

**Comment by CrazyVulcan** [comment]
Thanks for letting me know, it will be removed next update I push live.
