### ISSUE TITLE
data adjustments: missing ship classes and duplicate ID

### ISSUE THREAD

**Issue by FND** [KFNEXUS/KFNEXUS.github.io#51]
Analyzing the data (cf. #50), I've noticed the following issues (as of e655ed3256f03bb980cd63b9aa7b21b39415f620):

* [ ] `uss_enterprise_a_75005` references `Kelvin Constitution Class`, but there doesn't seem to be a corresponding entry in ship classes
* [ ] `iks_suvwl_75005` references `Warbird Class`, but there doesn't seem to be a corresponding entry in ship classes
* [ ] the ID `third_of_five_71525` is used for two separate entries: as a captain and as a crew upgrade

I'm not sure about the missing ship classes (where to get the data from?), but for the duplicate ID, I imagine we could just change the crew upgrade's ID (e.g. by adding `_b` to the end, similar to `maquis_raider_b`) without breaking anything?

@CrazyVulcan, you're much more familiar with the data, so I'm hoping you can recommend a way to address these issues.

**Comment by CrazyVulcan** [comment]
@FND Well the new Enterprise A and the IKS Suvwl have only been previewed and they are completely new class' of ships. As such I could only guess at what their dial looks like. I was just wanting to avoid false information in the Set Viewer in which I preview 20 cards from Origins game fair. I could just make an empty class for now with no data to get rid of the warning. 

the third_of_five_71525 is an easy enough fix.

**Comment by CrazyVulcan** [comment]
OK all errors are gone with the empty class quick fix and 3 of 5 has both a crew and captain from the same set and both had the same id. It just went uncaught until now.

**Comment by FND** [comment]
Excellent, thank you! Good call on the preliminary ship classes, that makes perfect sense.

**Comment by FND** [comment]
@CrazyVulcan: I've noticed that the Gurngouin (`gurngouin_75004`) lists "Maquis Raider" as its ship class (i.e. `"class": "Maquis Raider"`). However, as stated above, that's ambiguous - would you mind changing that to either `"classId": "maquis_raider"` or `"classId": "maquis_raider_b"`? (I'm not sure which is correct; `maquis_raider_b` additionally has 90° rear arc.)

PS: Please allow me to remind you of #52 while you're at it. 🙂

PPS: I'm back to working on the [consolidated data model](https://github.com/KFNEXUS/KFNEXUS.github.io/pull/50#issuecomment-401533415) and expect to have some details on that soon. That might be easier to discuss via e-mail; can I contact you on the GMail address you use for your Git commits?
